# hotel-pms/docker-compose.yml
version: '3.8'
services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:

# Monitoring

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Expose Prometheus UI on port 9090

  grafana:
    image: grafana/grafana-oss:9.5.3
    container_name: grafana
    ports:
      - "3000:3000" # Expose Grafana UI on port 3000
    depends_on:
      - prometheus