# hotel-pms/docker-compose.yml
version: '3.8'
services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data: