# hotel-management-system/prometheus.yml
global:
  scrape_interval: 15s # Scrape every 15 seconds

scrape_configs:
  - job_name: 'hotel-backend'
    static_configs:
      - targets: ['host.docker.internal:8080']